"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express = require('express');
var router = express.Router();
var Controller_1 = require("../Controller/Controller");
router.get('/allbooks', Controller_1.getAllBooks);
router.post('/add', Controller_1.AddBook);
router.patch('/update/:id', Controller_1.UpdateBook);
router.delete('/delete/:id', Controller_1.DeleteBook);
exports.default = router;
